apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-executor
  labels:
    app: executor
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: executor
  template:
    metadata:
      labels:
        app: executor
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "9090"
        prometheus.io/path: "/metrics"
    spec:
      serviceAccountName: {{ .Release.Name }}-executor
      containers:
        - name: executor
          image: "{{ .Values.services.executor.image }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: KAFKA_BROKER
              value: "{{ .Release.Name }}-kafka:9092"
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Release.Name }}-executor
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ .Release.Name }}-executor
rules:
  - apiGroups: ["apps"]
    resources: ["deployments", "replicasets"]
    verbs: ["get", "list", "patch", "update"]
  - apiGroups: ["apps"]
    resources: ["deployments/scale"]
    verbs: ["get", "patch", "update"]
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "list", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ .Release.Name }}-executor
subjects:
  - kind: ServiceAccount
    name: {{ .Release.Name }}-executor
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: {{ .Release.Name }}-executor
  apiGroup: rbac.authorization.k8s.io
